version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: portal_b2b
      MYSQL_USER: nata
      MYSQL_PASSWORD: 12345678
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
